### ISSUE TITLE
foreground and background don't work for Button

### ISSUE THREAD

**Issue by igotfr** [redox-os/orbtk#424]
**Describe the bug**
foreground and background don't work for Button

**To Reproduce**

<code>main_view.rs</code>

```rust
use orbtk::prelude::*;

use crate::MainState;

widget!(
  MainView<MainState> {
    title: String
  }
);

impl Template for MainView {
  fn template(self, id: Entity, ctx: &mut BuildContext) -> Self {
    self.name("MainView").child(
      Button::new()
        .text(("title", id))
        .background("#db0fb6")
        .foreground("#db0fb6")
        .build(ctx))
  }
}
```

**Expected behavior**
Buton with color #db0fb6 on background or foreground

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 10

**Additional context**
<code>Cargo.toml</code>

```toml
[package]
name = "orb"
version = "0.1.0"
authors = ["usuario"]
edition = "2018"
readme = "README.md"
license = "MIT"

[profile.dev]
opt-level = 1

[features]
debug = ["orbtk/debug"]

[dependencies]
orbtk = { git = "https://github.com/redox-os/orbtk.git", branch= "develop" }
```
