### ISSUE TITLE
Text looks vague in macos

### ISSUE THREAD

**Issue by goflutterjava** [redox-os/orbtk#480]
**Screenshots**
<img width="778" alt="image" src="https://user-images.githubusercontent.com/95280282/154830701-02594639-a9d8-4b60-9b0d-1c0a5689e475.png">

**Desktop (please complete the following information):**
 - OS: osx
 - Darwin 192.168.0.102 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
<img width="550" alt="image" src="https://user-images.githubusercontent.com/95280282/154830709-1f64a3c8-1515-466a-aedc-35dcf949fcb5.png">

```toml
[dependencies]
orbtk = "0.3.1-alpha3"
```

```rust
use orbtk::prelude::{Application, TextBlock, Widget, Window};

fn main() {
    Application::new()
        .window(|ctx| {
            Window::new()
                .title("Dev Tools")
                .position((100.0, 100.0))
                .size(1200.0, 800.0)
                .child(TextBlock::new().text("Dev Tools").build(ctx))
                .build(ctx)
        })
        .run();
}
```

**Comment by rzerres** [comment]
@goflutterjava please can you recheck using `OrbTk`'s development branch? This will be tagged as "0.3.1-alpha4" soon.

**Comment by goflutterjava** [comment]
@rzerres When I use the `development` branch, it raises another error.
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/95280282/154849482-7942cf0a-7c2b-486c-a96f-44a384e9c24f.png">

**Comment by rzerres** [comment]
did you go with a 

```
cargo clean
cargo update
```
it is working for me on x64_86 architecture. Sorry, can't test on OSX.
You may also make use of the `bundled` feature, as described in the README.md.
I copied you code to `orbtk/examples/dev_tools.rs`
 
```rust
use orbtk::prelude::*;

fn main() {
    Application::new()
        .window(|ctx| {
            Window::new()
                .title("Dev Tools")
                .position((100.0, 100.0))
                .size(1200.0, 800.0)
                .child(TextBlock::new().text("Dev Tools").build(ctx))
                .build(ctx)
        })
        .run();
}
```

then called:

```
cargo run  --features bundled --example dev_tools
```

**Comment by goflutterjava** [comment]
I have run 
```
cargo clean
cargo update
```
it now raise

```
cargo run --features bundled main.rs
error: none of the selected packages contains these features: bundled
```

and this is my toml
```toml
[package]
name = "dev-tools-rust-orbtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#orbtk = "0.3.1-alpha4"
orbtk = { git = "https://github.com/redox-os/orbtk.git", branch = "develop"}

```
Please take a look when you have time, thanks
